<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">

   <title>Zoiper Branduin</title>

   <link rel="stylesheet" href="<?=asset('/css/bootstrap/3.3/css/bootstrap.css')?>"/>
   <link rel="stylesheet" href="<?=asset('/css/bootstrap/3.3/css/bootstrap-theme.css')?>"/>
   <link rel="stylesheet" href="<?=asset('/css/bootstrap/assets/css/ie10-viewport-bug-workaround.css')?>">
   <!--[if lt IE 9]>
   <script src="<?=asset('/js/html5shiv-3.7.3.min.js')?>"></script>
   <script src="<?=asset('/js/respond-1.4.2.min.js')?>"></script>
   <![endif]-->
   <script src="<?=asset('/js/jquery/jquery-1.12.4.js')?>"></script>
   <script src="<?=asset('/css/bootstrap/3.3/js/bootstrap.js')?>"></script>
   <script src="<?=asset('/css/bootstrap/assets/js/ie10-viewport-bug-workaround.js')?>"></script>

   <link rel="stylesheet" href="<?=asset('/css/app.css')?>">
   <script src="<?=asset('/js/rosasurfer.js')?>"></script>
   <script src="<?=asset('/js/app.js')?>"></script>
</head>

<body>
   <?$navigation->render()?>

   <div class="container">
      <?$content->render()?>
   </div>
</body>
</html>
