<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">

   <title>BFX test server</title>
</head>

<body>
Proof of concept for the supposed but fake BankersFX volume data feed.

<?
/** @var Request $request */
foreach ($request->getActionMessages() as $message) {?>
    <div class="alert alert-danger textcenter"><p><?=hsc($message)?></p></div>
<?}?>
</body>
</html>
