<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">

   <title>BFX demo server</title>
</head>

<body>
Test case proving that the BankersFX Core Volume indicator does not use institutional data.

<?php
use rosasurfer\ministruts\Request;

use function rosasurfer\hsc;

/** @var Request $request */
foreach ($request->getActionMessages() as $message) {?>
    <div class="alert alert-danger textcenter"><p><?=hsc($message)?></p></div>
<?php } ?>

</body>
</html>
